### ISSUE TITLE
Presigned URL?

### ISSUE THREAD

**Issue by tmikaeld** [bradenmacdonald/deno-s3-lite-client#2]
Awesome project, glad to see more Deno specific modules, especially something so tiny!

I was in need of [pre-signed URL](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property) here too, all parts seem to be in the signing parts already.

Is this something you can add?

**Comment by bradenmacdonald** [comment]
Thanks! It turns out I also need pre-signed URLs so I'm planning to implement it soon :)

**Comment by bradenmacdonald** [comment]
Added in v0.2.0: https://github.com/bradenmacdonald/deno-s3-lite-client/releases/tag/0.2.0
