### ISSUE TITLE
Abort the request with AbortSignal

### ISSUE THREAD

**Issue by alexgleason** [bradenmacdonald/deno-s3-lite-client#24]
I want to pass an `AbortSignal`  into `s3.putObject()` and `s3.deleteObject()`, eg `s3.deleteObject('myObj', { signal })`

That way I can cancel the upload if the user cancels the request:

```ts
s3.putObject('myObj', bytes, { signal: c.req.signal })
```

Or I can cancel the upload after a certain period of time:

```ts
s3.putObject('myObj', bytes, { signal: AbortSignal.timeout(5000) })
```

I took a stab at making the change myself, but it would require changing too many files I'm not familiar with. This is a start:

```diff
diff --git a/client.ts b/client.ts
index 2e950b7..358aed1 100644
--- a/client.ts
+++ b/client.ts
@@ -212,7 +212,7 @@ export class Client {
   /**
    * Make a single request to S3
    */
-  public async makeRequest({ method, payload, ...options }: {
+  public async makeRequest({ method, payload, signal, ...options }: {
     method: "POST" | "GET" | "PUT" | "DELETE" | string;
     headers?: Headers;
     query?: string | Record<string, string>;
@@ -229,6 +229,8 @@ export class Client {
      * the caller can read it.
      */
     returnBody?: boolean;
+    /** Signal to abort the request. */
+    signal?: AbortSignal;
   }): Promise<Response> {
     const date = new Date();
     const { headers, host, path } = this.buildRequestOptions(options);
@@ -273,6 +275,7 @@ export class Client {
       method,
       headers,
       body: payload,
+      signal,
     });
 
     if (response.status !== statusCode) {
```

To complete this, all functions that call `makeRequest()` need to accept a signal, and then pass it down.

**Comment by bradenmacdonald** [comment]
Sorry for the slow reply. I think this is doable, along the lines that you sketched out. I'm just wondering if it's necessary? If you're doing any long-lived requests, you're probably using the streams API, and it already provides a way to inject a signal as well as cancel the request:

```ts
const downloadResult = await client.getObject(destKey);
const file = await Deno.open("outfile.dat", {write: true});
const controller = new AbortController();
downloadResult.body?.pipeTo(file.writable, {signal: controller.signal});
```
or `downloadResult.body?.getReader().cancel();` will also cancel it.

Would one of those approaches cover your use case? Or is there a unique benefit to specifying a `signal` at the `fetch` level?

**Comment by alexgleason** [comment]
I didn't know that was possible. Thank you for the explanation and example! :clap:

**Comment by bradenmacdonald** [comment]
You're welcome! Though as I said, I haven't tried these myself. So feel free to re-open if you find something still missing.
