### ISSUE TITLE
Bucket creation functionality

### ISSUE THREAD

**Issue by thepocp** [bradenmacdonald/deno-s3-lite-client#25]
I'm reaching out to suggest adding makeBucket function to the library. As it stands, I couldn't find this feature. If this function is already available and I've overlooked it, I'd appreciate guidance on its usage. If not, its inclusion could greatly benefit developers needing to manage buckets programmatically.

I'm grateful for your efforts in developing this library, and I'm willing to contribute to implementing this feature

**Comment by bradenmacdonald** [comment]
There is not currently any make bucket functionality included. I'd be happy to include it if you're willing to implement it! Ideally including a test case with MinIO like the other integration tests.

**Comment by thepocp** [comment]
I've added features for bucket management: `bucketExists`, `makeBucket` and `removeBucket`, along with MinIO integration tests. Please see the PR for details. Feedback is welcome!
#27

**Comment by bradenmacdonald** [comment]
Now available in version 0.7.0. Thanks!
