### ISSUE TITLE
copyObject?

### ISSUE THREAD

**Issue by tmikaeld** [bradenmacdonald/deno-s3-lite-client#4]
Hello again!

I'd love to be able to copy files:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html

It seems the only thing that needs to be added is: `x-amz-copy-source` header.

**Comment by bradenmacdonald** [comment]
Hi @tmikaeld I can implement that for you eventually... why did you close this?

**Comment by tmikaeld** [comment]
@bradenmacdonald I didn't want to burden you with it, so I added it and other modifications (like returning the response to the parent). Didn't have time to do a PR yet, will do when I have more time..
