### ISSUE TITLE
requestResource in canonical string generation should be urlencoded

### ISSUE THREAD

**Issue by wyozi** [bradenmacdonald/deno-s3-lite-client#8]
Trying to retrieve a resource from s3 e.g. `/my/folder/työnantaja.pdf` fails, because the `ö` character in canonical string generation is not urlencoded properly.

Passing it through `encodeURI` (i.e. `canonical.push(encodeURI(requestResource));`) makes the above request work.

Don't ask why paths like this are stored in our s3 bucket 😬

**Comment by bradenmacdonald** [comment]
Fixed in v0.5. Thanks for the report!
